server:
  port: ${port}
eureka:
  instance:
    hostname: peer1 #eureka服务端的实例名称
  client:
    #register-with-eureka: false #false表示不向注册中心注册自己
    #fetch-registry: false #自己就是注册中心，不需要去检索服务
    service-url:
      # 设置与EurekaServer 交互的地址 （查询服务和注册服务都需要依赖该地址）
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://peer2:7002/eureka/,http://peer3:7003/eureka/
spring:
  application:
    name: eureka-server # 搭建集群时，多个实例的name需保持一致